### ISSUE TITLE
helix editor unable to perform codeAction

### ISSUE THREAD

**Issue by tanj** [hangyav/textLSP#3]
The helix editor always sends a selection width of one character for `codeAction`, because helix way is "always be selecting." This will always result in sending at least a range of 1 and textLSP returning the error `Code action is not supported for range.` instead of corrections.

**Comment by hangyav** [comment]
Thank you for reporting this issue. Things are still a bit rough around the edges. I'll put this on my priority list.

**Comment by hangyav** [comment]
I added this "feature". Please check with the latest version on github.

**Comment by tanj** [comment]
working for me with the latest version.

Thanks so much!
