### ISSUE TITLE
nvim-lspconfig nonfunctional, does not show under `Configured server list` nor attach

### ISSUE THREAD

**Issue by uwidev** [hangyav/textLSP#34]
textlsp does not seem to be detected after installation using nvim-lspconfig. Is there more I'm supposed to do after adding it under the config?

<details>
<summary>Relevant but gutted init.lua</summary>

```lua
require('lazy').setup({
  { -- LSP Configuration & Plugins
    'neovim/nvim-lspconfig',
    dependencies = {
      { 'williamboman/mason.nvim', config = true }, -- NOTE: Must be loaded before dependants
      'williamboman/mason-lspconfig.nvim',
      'WhoIsSethDaniel/mason-tool-installer.nvim',
      { 'j-hui/fidget.nvim', opts = {} },
      { 'folke/neodev.nvim', opts = {} },
    },

    config = function()
      vim.api.nvim_create_autocmd('LspAttach', {
        group = vim.api.nvim_create_augroup('kickstart-lsp-attach', { clear = true }),
        callback = function(event)
          -- keybind mappings would go here
          -- removed for clarity

          local client = vim.lsp.get_client_by_id(event.data.client_id)
          if client and client.server_capabilities.documentHighlightProvider then
            local highlight_augroup = vim.api.nvim_create_augroup('kickstart-lsp-highlight', { clear = false })
            vim.api.nvim_create_autocmd({ 'CursorHold', 'CursorHoldI' }, {
              buffer = event.buf,
              group = highlight_augroup,
              callback = vim.lsp.buf.document_highlight,
            })

            vim.api.nvim_create_autocmd({ 'CursorMoved', 'CursorMovedI' }, {
              buffer = event.buf,
              group = highlight_augroup,
              callback = vim.lsp.buf.clear_references,
            })

            vim.api.nvim_create_autocmd('LspDetach', {
              group = vim.api.nvim_create_augroup('kickstart-lsp-detach', { clear = true }),
              callback = function(event2)
                vim.lsp.buf.clear_references()
                vim.api.nvim_clear_autocmds { group = 'kickstart-lsp-highlight', buffer = event2.buf }
              end,
            })
          end
        end,
      })

      local capabilities = vim.lsp.protocol.make_client_capabilities()
      capabilities = vim.tbl_deep_extend('force', capabilities, require('cmp_nvim_lsp').default_capabilities())

      local servers =
        {
          tsserver = {
            cmd = { 'typescript-language-server', '--stdio' },
          },

          -- python
          ruff_lsp = {},
          jedi_language_server = {},

          -- shell/bash scripting
          bashls = {},

          -- lua
          lua_ls = {
            settings = {
              Lua = {
                completion = {
                  callSnippet = 'Replace',
                },
              },
            },
          },

          -- regular text
          textlsp = {},
        },
        -- Ensure the servers and tools above are installed
      local ensure_installed = vim.tbl_keys(servers or {})
      vim.list_extend(ensure_installed, {
        'stylua', -- Used to format Lua code
        'shellcheck',
        'shfmt',
      })
      require('mason-tool-installer').setup { ensure_installed = ensure_installed }

      require('mason-lspconfig').setup {
        handlers = {
          function(server_name)
            local server = servers[server_name] or {}
            -- This handles overriding only values explicitly passed
            -- by the server configuration above. Useful when disabling
            -- certain features of an LSP (for example, turning off formatting for tsserver)
            server.capabilities = vim.tbl_deep_extend('force', {}, capabilities, server.capabilities or {})
            require('lspconfig')[server_name].setup(server)
          end,
        },
      }
    end,
  },
})
```
</details>

`LspInfo` when a buffer is open of file `a.text`
![image](https://github.com/hangyav/textLSP/assets/10101319/2fa25d41-583b-4dc6-a831-5512213681f7)

`Mason`
![image](https://github.com/hangyav/textLSP/assets/10101319/4517175b-7fa0-4a76-b8dd-2afa9db13750)

I have also tried the default config provided under readme as well as manual defaults from [nvim-lspconfig](https://github.com/neovim/nvim-lspconfig/blob/master/doc/server_configurations.md#textlsp) and it also does not work.

**Comment by hangyav** [comment]
Based on a quick look at your config this should work. Do you get any error messages when opening a text file with nvim? It's odd that textlsp's icon in the mason list is gray. Is there any particular reason for that? Could you verify that it is actually installed under `~/.local/share/nvim/mason/packages`?

**Comment by uwidev** [comment]
> It's odd that textlsp's icon in the mason list is gray. Is there any particular reason for that?

It's my theme. Whatever my text is over is colored grey.

I get no errors whatsoever when opening any `.text` files. I tried the `.org` and `.tex` and no responses at all.

> Could you verify that it is actually installed under ~/.local/share/nvim/mason/packages?

```bash
~/.local/share/nvim/mason/packages
 ls
bash-language-server             ruff-lsp                   stylua
css-lsp                          rust-analyzer              tailwindcss-language-server
docker-compose-language-service  shellcheck                 textlsp
jedi-language-server             shfmt                      typescript-language-server
lua-language-server              some-sass-language-server  typos-lsp

 ls textlsp
mason-receipt.json  venv

 ls textlsp/venv
bin  include  lib  lib64  pyvenv.cfg  share

 ls textlsp/venv/bin
activate       convert-caffe2-to-onnx  httpx            numpy-config  pip3.12     textlsp
activate.csh   convert-onnx-to-caffe2  huggingface-cli  openai        python      torchrun
activate.fish  distro                  isympy           pip           python3     tqdm
Activate.ps1   f2py                    normalizer       pip3          python3.12  transformers-cli
```

I forgot to mention this, but I am using neovim `v0.11.0-dev-283+gfe5d1279a4`.

**Comment by uwidev** [comment]
onfirm

**Comment by uwidev** [comment]
It seems that it's because `textlsp` is not registered in [williamboman/mason-lspconfig](https://github.com/williamboman/mason-lspconfig.nvim?tab=readme-ov-file#available-lsp-servers) repository. If you want I can go ahead and issue a pull request over there to implement textlsp. It doesn't look that hard since it seems like it's just 3 line additions across 3 files, but I'm also not sure if you need to do more.

Locally on my machine, I edited `mason-lspconfig` to add the mapping for textlsp and the plugin loaded. I have yet to test if the rest of the functionality works.

**Comment by hangyav** [comment]
Thanks for looking into this. I'm not familiar with how kickstart is configured, but I tested it with a clean [LazyVim](https://www.lazyvim.org/installation) installation that uses [mason-registry](https://github.com/mason-org/mason-registry) and a simple `.config/nvim/lua/plugins/lspconfig.lua` config:

```lua
return {
	"neovim/nvim-lspconfig",
	opts = {
		servers = {
			textlsp = {},
		},
	},
}
```

After installing textlsp with `MasonInstall textlsp` manually, it worked. So just for future reference to others running into similar issues since I'm not too familiar with the works of Mason either, what was the main issue? You need to make sure `mason-registry` is included in the config or we need to add textlsp to [williamboman/mason-lspconfig](https://github.com/williamboman/mason-lspconfig.nvim)?

Answering your other questions:

> Just to confirm, I should have LanguageTool installed on my system just to test of the plugin can connect, right? I'm using Archlinux and I installed thorugh the AUR. Was that all that had to be done to test if the plugin works?

For the LanguageTool analyser you only need to make sure that Java is installed, the tool itself is installed automatically. Otherwise, it should be good to go (by default only the LanguageTool analyser is enabled).

> It seems that it's because textlsp is not registered in [williamboman/mason-lspconfig](https://github.com/williamboman/mason-lspconfig.nvim?tab=readme-ov-file#available-lsp-servers) repository. If you want I can go ahead and issue a pull request over there to implement textlsp. It doesn't look that hard since it seems like it's just 3 line additions across 3 files, but I'm also not sure if you need to do more.

It would be nice if you could do that, thanks!

> when trying to use Ollama, I get the following error message.
LSP[textlsp] Unsupported module: textLSP.analysers.ollama

Yeah, for now Ollama is in the latest github version only. I'll release it to pypi hopefully soon.

**Comment by uwidev** [comment]
> So just for future reference to others running into similar issues since I'm not too familiar with the works of Mason either, what was the main issue? You need to make sure mason-registry is included in the config or we need to add textlsp to [williamboman/mason-lspconfig](https://github.com/williamboman/mason-lspconfig.nvim)?

As far as I'm aware, mason-lspconfig is a wrapper of sorts for mason and nvim-lspconfig. More or less it automatically fetches the related mason package and sets it up for you via lspconfig; it just trivializes the process. That said, it only works if an lsp name passed to it is actually registered. This is because lspconfig and mason use slightly different naming conventions, so this mapping is required to map the mason package to the lspconfig setup.

If you take a look at some of the [example pull requests](https://github.com/williamboman/mason-lspconfig.nvim/pull/425/commits/cd3d935b634fc5fcf16138d0814f01b3499a0eb6), it's really quite simple. [The pull request has been made.](https://github.com/williamboman/mason-lspconfig.nvim/pull/433)

**For anyone using mason-lspconfig, their options at the moment are to manually apply the mason-lspconfig edits themselves (as seen above, but with `["textlsp"] = "textlsp"`) on their local install or manually call `setup()`.**
