### ISSUE TITLE
[Feature suggestion]: Part-of-speech highlighting

### ISSUE THREAD

**Issue by SichangHe** [hangyav/textLSP#38]
Hey, since this is a text language server, would you be interested in adding syntax highlighting?

I did some experiment (https://github.com/SichangHe/natural_syntax), but it sucks to install because of Rust-BERT and libtorch. I guess something like https://github.com/flairNLP/flair/ would be better, so it makes sense to have it in Python instead.

Please let me know what you think, and then I could share more information.

\
Thanks!\
Steven Hé (Sīchàng)

**Comment by hangyav** [comment]
Hi,

Thanks for the suggestion. Could you tell a bit more about the use case of this feature? Would you use it in any special case or in general?  Is it only POS based highlighting or are there other options as well? Other than plain text files, e.g., markdown or latex, have syntax highlighting of their own. How would these play together (technically I guess you either use the editor's or the LSP's highlighting)?

**Comment by SichangHe** [comment]
> Could you tell a bit more about the use case of this feature? Would you use it in any special case or in general?

Highlighting code definitely makes them easier to read (after you get used to it); highlighting text may have similar effects. This shows especially when the reader is having fatigue.

> Is it only POS based highlighting or are there other options as well?

I have not explored other options. I did see [an attention-based highlighting](https://github.com/jiesutd/YATO?tab=readme-ov-file#text-attention-heatmap-visualization), but it looks like very inaccurate.

> Other than plain text files, e.g., markdown or latex, have syntax highlighting of their own. How would these play together (technically I guess you either use the editor's or the LSP's highlighting)?

This is a good question. It is a pain in the ass. To actually support text with markup, you would need to parse them, remove the markup (unless your model can deal with markup), feed it into the model, map the result back to the text, then add the markup highlighting on top. LSP semantic highlights usually are set to overwrite regex and Tree-sitter.

With that said, this is non-trivial. I am throwing it out here to see if there are interests in it.

**Comment by hangyav** [comment]
The POS-based full highlighting is a bit too much for me personally but highlighting e.g. just named entities could be interesting.

That said I'm worried about mixing this with markup highlight. One of the main goals of textLSP is to support markup languages. Currently I'd say it quite easy to add now file types, but if we also need to implement markup highlighting that might make things difficult and  textLSP quite heavy (although with TreeSitter it might not be that difficult but I'm not sure).

 I am not totally against the idea but as you can see from the frequency of my answers, unfortunately I don't have as much time to spend on the project as I'd like to. So if you are still interested despite the markup highlighting issues, could you draft a proposal of how this could be implemented in the current framework?

**Comment by justinlovinger** [comment]
I am confused as to how part-of-speech highlighting is relevant to this project. I thought this project was for spelling and grammar checking using AI-tools, not syntax-highlighting.

Also, I have never heard of a language-server being used for syntax-highlighting. How would that work? From what I have seen, most editors only support highlighting specific diagnostics from a language-server, and the manner of highlighting is up to the editor. This feature seems better suited as a plugin for an editor.

**Comment by hangyav** [comment]
Yep, I agree with you that highlighting is a bit out of scope, especially considering the difficulties combining the POS idea with markup highlight. However, since we do document parsing and have a framework for AI models, it is somewhat related. Anyways, since there wasn't much activity related to this, I'm closing the issue.
