### ISSUE TITLE
OpenAI text correction : possibility to modify prompt on configuration?

### ISSUE THREAD

**Issue by mahaaaham** [hangyav/textLSP#44]
Hi

This is maybe a very naive question, as I am not at ease with these tools.

I would like if there is a way to "fine-tune" the behavior of open AI text correct through a prompt, in the configuration of textlsp? For example, I would like to indicate the kind of document and tone, in order for it to find more mistakes.

For information, I use nvim with nvim-lspconfig and mason. 

Thank you for your tool and for reading me!

**Comment by hangyav** [comment]
Hi,

Yes, this is already supported. You can use the `edit_instruction` property to set the prompt used for checking for errors:

```lua
textLSP = {
    analysers = {
        openai = {
            ...
            edit_instruction = 'Fix spelling and grammar errors.', -- This is the default
            ...
        },
    },
}
```

Please let us know if you come up with some interesting prompts ;)

**Comment by mahaaaham** [comment]
Thank you! My prompt will sadly be very specific, I guess ^^. I want English correction for a math article.
